const String WelcomePageTitle = 'welcome_page_title',
    WelcomePageSubtitle = 'welcome_page_subtitle',
    WelcomePageLoginButtonLabel = 'welcome_page_login_button_label',
    WelcomePageRegisterButtonLabel = 'welcome_page_register_button_label',
    OnBoardingUserNameTitle = 'on_boarding_username_title',
    OnBoardingUserNameHint = 'on_boarding_username_hint',
    OnBoardingUserNameLabel = 'on_boarding_username_label',
    OnBoardingSexAndAgeTitle = 'on_boarding_sex_and_age_title',
    YourSex = "your_sex",
    Man = "man",
    Woman = "woman",
    NC = "nc",
    GetBirthdayLabel = "get_birthday_label",
    January = "january",
    February = "february",
    March = "march",
    April = "april",
    May = "may",
    June = "june",
    July = "july",
    August = "august",
    September = "september",
    October = "october",
    November = "novemnber",
    December = "december",
    Validate = "validate";

final fr = {
  WelcomePageTitle: "Hello, moi c'est CARL !",
  WelcomePageSubtitle: "L'assistant de fidélité soucieux de votre vie privée",
  WelcomePageLoginButtonLabel: "J'ai déjà un compte",
  WelcomePageRegisterButtonLabel: "Salut Carl !",
  OnBoardingUserNameTitle: "Heureux de te rencontrer,\ncomment tes amis t'appellent ?",
  OnBoardingUserNameHint: "Ils m'appellent...",
  OnBoardingUserNameLabel: "Votre prénom",
  OnBoardingSexAndAgeTitle:
      "Avec Carl, ces informations ne seront jamais reliées à votre identité !\nVous serez, aux yeux des commerçants, un utilisateur anonyme.",
  YourSex: "Votre sexe",
  Man: "Homme",
  Woman: "Femme",
  NC: "N.C",
  GetBirthdayLabel: "Pour recevoir une surprise le jour de votre anniversaire",
  January: "Janvier",
  February: "Fevrier",
  March: "Mars",
  April: "Avril",
  May: "Mai",
  June: "Juin",
  July: "Juillet",
  August: "Aout",
  September: "Septembre",
  October: "Octobre",
  November: "Novembre",
  December: "Décembre",
  Validate: "Valider"
};

final en = {
  WelcomePageTitle: "Wecome, I'm Carl !",
  WelcomePageSubtitle: "The fidelity's assistant that cares about privacy",
  WelcomePageLoginButtonLabel: "I have an account",
  WelcomePageRegisterButtonLabel: "Hi Carl !",
  OnBoardingUserNameTitle: "Nice to meet you,\nhow do your friends call you ?",
  OnBoardingUserNameHint: "They call me...",
  OnBoardingUserNameLabel: "Your first name",
  OnBoardingSexAndAgeTitle:
      "With Carl, these informations will never be linked to your identity !\nYou will be, for the merchants, an anonymous user.",
  YourSex: "Your sex",
  Man: "Man",
  Woman: "Woman",
  NC: "N.C",
  GetBirthdayLabel: "To receive a surprise on your birthday",
  January: "January",
  February: "February",
  March: "March",
  April: "April",
  May: "May",
  June: "June",
  July: "July",
  August: "August",
  September: "September",
  October: "October",
  November: "Novemnber",
  December: "December",
  Validate: "Validate"
};
