const String WelcomePageTitle = 'welcome_page_title',
    WelcomePageSubtitle = 'welcome_page_subtitle',
    WelcomePageLoginButtonLabel = 'welcome_page_login_button_label',
    WelcomePageRegisterButtonLabel = 'welcome_page_register_button_label',
    OnBoardingUserNameTitle = 'on_boarding_username_title',
    OnBoardingUserNameHint = 'on_boarding_username_hint',
    OnBoardingUserNameLabel = 'on_boarding_username_label',
    OnBoardingSexAndAgeTitle = 'on_boarding_sex_and_age_title',
    YourSex = "your_sex",
    Man = "man",
    Woman = "woman",
    NC = "nc",
    GetBirthdayLabel = "get_birthday_label",
    January = "january",
    February = "february",
    March = "march",
    April = "april",
    May = "may",
    June = "june",
    July = "july",
    August = "august",
    September = "september",
    October = "october",
    November = "novemnber",
    December = "december",
    Validate = "validate",
    Add = "add",
    EmptyCardsTitle = "emptyCardsTitle",
    EmptyCardsDescription = "emptyCardsDescription",
    ErrorServerTitle = "errorServerTitle",
    ErrorServerDescription = "errorServerDescription",
    VisitsHistoricTitle = "visitsHistoricTitle",
    At = "at",
    EmptyGoodDealsTitle = "emptyGoodDealsTitle",
    EmptyGoodDealsDescription = "emptyGoodDealsDescription",
    Monday = "monday",
    Tuesday = "tuesday",
    Wednesday = "wednesday",
    Thursday = "thursday",
    Friday = "friday",
    Saturday = "saturfay",
    Sunday = "sunday";

final fr = {
  WelcomePageTitle: "Hello, moi c'est CARL !",
  WelcomePageSubtitle: "L'assistant de fidélité soucieux de votre vie privée",
  WelcomePageLoginButtonLabel: "J'ai déjà un compte",
  WelcomePageRegisterButtonLabel: "Salut Carl !",
  OnBoardingUserNameTitle: "Heureux de te rencontrer,\ncomment tes amis t'appellent ?",
  OnBoardingUserNameHint: "Ils m'appellent...",
  OnBoardingUserNameLabel: "Votre prénom",
  OnBoardingSexAndAgeTitle:
      "Avec Carl, ces informations ne seront jamais reliées à votre identité !\nVous serez, aux yeux des commerçants, un utilisateur anonyme.",
  YourSex: "Votre sexe",
  Man: "Homme",
  Woman: "Femme",
  NC: "N.C",
  GetBirthdayLabel: "Pour recevoir une surprise le jour de votre anniversaire",
  January: "Janvier",
  February: "Fevrier",
  March: "Mars",
  April: "Avril",
  May: "Mai",
  June: "Juin",
  July: "Juillet",
  August: "Aout",
  September: "Septembre",
  October: "Octobre",
  November: "Novembre",
  December: "Décembre",
  Validate: "Valider",
  Add: "Ajouter",
  EmptyCardsTitle: "Aucune carte de fidélité",
  EmptyCardsDescription: "Cliquer sur le bouton ci-dessous pour scanner votre première carte !",
  ErrorServerTitle: "Une erreur est survenue",
  ErrorServerDescription: "Veuillez ré-essayer ultérieurement",
  VisitsHistoricTitle: "Historique des visites",
  At: "A",
  EmptyGoodDealsTitle: "Aucun bon plan",
  EmptyGoodDealsDescription:
      "Ici se trouveront les futurs bons plans partagés par les professionnels !",
  Monday: "lundi",
  Tuesday: "mardi",
  Wednesday: "mercredu",
  Thursday: "jeudi",
  Friday: "vendredi",
  Saturday: "samedi",
  Sunday: "dimanche",
};

final en = {
  WelcomePageTitle: "Wecome, I'm Carl !",
  WelcomePageSubtitle: "The fidelity's assistant that cares about privacy",
  WelcomePageLoginButtonLabel: "I have an account",
  WelcomePageRegisterButtonLabel: "Hi Carl !",
  OnBoardingUserNameTitle: "Nice to meet you,\nhow do your friends call you ?",
  OnBoardingUserNameHint: "They call me...",
  OnBoardingUserNameLabel: "Your first name",
  OnBoardingSexAndAgeTitle:
      "With Carl, these informations will never be linked to your identity !\nYou will be, for the merchants, an anonymous user.",
  YourSex: "Your sex",
  Man: "Man",
  Woman: "Woman",
  NC: "N.C",
  GetBirthdayLabel: "To receive a surprise on your birthday",
  January: "January",
  February: "February",
  March: "March",
  April: "April",
  May: "May",
  June: "June",
  July: "July",
  August: "August",
  September: "September",
  October: "October",
  November: "Novemnber",
  December: "December",
  Validate: "Validate",
  Add: "Add",
  EmptyCardsTitle: "No fidlity cards",
  EmptyCardsDescription: "Click on button to start scanning your first card !",
  ErrorServerTitle: "An error occured",
  ErrorServerDescription: "Please try again later",
  VisitsHistoricTitle: "Visits historic",
  At: "At",
  EmptyGoodDealsTitle: "No Good Deals",
  EmptyGoodDealsDescription: "Here will be the future good deals provided by pros !",
  Monday: "monday",
  Tuesday: "tuesday",
  Wednesday: "wednesday",
  Thursday: "thursday",
  Friday: "friday",
  Saturday: "saturday",
  Sunday: "sunday",
};
