name: carl
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^0.10.1
  bloc: ^0.11.2
  http: 0.12.0
  equatable: 0.1.6
  flutter_swiper: 1.1.5
  shared_preferences: ^0.5.2
  image_ink_well: ^0.1.0
  flutter_launcher_icons: ^0.7.0
  image: 2.0.7
  firebase_core: ^0.4.0
  firebase_messaging: ^5.0.1+1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.0.0

flutter_icons:
  ios: true
  android: true
  image_path: "assets/carl_logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/carl_face.png
  - assets/3.0x/carl_face.png
  - assets/2.0x/carl_face.png
  - assets/1.5x/carl_face.png
  - assets/1.0x/carl_face.png
  - assets/ic_carl.png
  - assets/3.0x/ic_carl.png
  - assets/2.0x/ic_carl.png
  - assets/1.5x/ic_carl.png
  - assets/1.0x/ic_carl.png
  - assets/ic_bell_card.png
  - assets/3.0x/ic_bell_card.png
  - assets/2.0x/ic_bell_card.png
  - assets/1.5x/ic_bell_card.png
  - assets/1.0x/ic_bell_card.png
  - assets/ic_search.png
  - assets/3.0x/ic_search.png
  - assets/2.0x/ic_search.png
  - assets/1.5x/ic_search.png
  - assets/1.0x/ic_search.png
  - assets/ic_settings.png
  - assets/3.0x/ic_settings.png
  - assets/2.0x/ic_settings.png
  - assets/1.5x/ic_settings.png
  - assets/1.0x/ic_settings.png
  - assets/ic_bell_card.png
  - assets/3.0x/ic_bell_card.png
  - assets/2.0x/ic_bell_card.png
  - assets/1.5x/ic_bell_card.png
  - assets/1.0x/ic_bell_card.png
  - assets/ic_bell.png
  - assets/3.0x/ic_bell.png
  - assets/2.0x/ic_bell.png
  - assets/1.5x/ic_bell.png
  - assets/1.0x/ic_bell.png
  - assets/ic_option.png
  - assets/3.0x/ic_option.png
  - assets/2.0x/ic_option.png
  - assets/1.5x/ic_option.png
  - assets/1.0x/ic_option.png
  - assets/ic_close.png
  - assets/3.0x/ic_close.png
  - assets/2.0x/ic_close.png
  - assets/1.5x/ic_close.png
  - assets/1.0x/ic_close.png
  - assets/carl_logo.png
  - assets/3.0x/carl_logo.png
  - assets/2.0x/carl_logo.png
  - assets/1.5x/carl_logo.png
  - assets/1.0x/carl_logo.png
  - assets/empty_cards.png
  - assets/3.0x/empty_cards.png
  - assets/2.0x/empty_cards.png
  - assets/1.5x/empty_cards.png
  - assets/1.0x/empty_cards.png

  - assets/notification_off.png

  - animations/
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
